const SET_USER_PROFILE_INFO = 'social-network/profile/SET_USER_PROFILE_INFO';
const SET_USER_STATUS = 'social-network/profile/SET_USER_STATUS';
const TOGGLE_IS_FETCHING_PROFILE_INFO =
  'social-network/profile/TOGGLE_IS_FETCHING_PROFILE_INFO';
const TOGGLE_IS_FETCHING_PROFILE_STATUS =
  'social-network/profile/TOGGLE_IS_FETCHING_PROFILE_STATUS';

const SET_USER_PHOTOS = 'social-network/profile/SET_USER_PHOTOS';

export {
  SET_USER_PROFILE_INFO,
  SET_USER_STATUS,
  SET_USER_PHOTOS,
  TOGGLE_IS_FETCHING_PROFILE_INFO,
  TOGGLE_IS_FETCHING_PROFILE_STATUS,
};
